apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: vault-forge-app
    count: 2
patches:
  - target:
      kind: Deployment
      name: vault-forge-app
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          environment: dev
