apiVersion: v1
kind: Service
metadata:
  name: vault-forge-app
  namespace: vault-forge
spec:
  selector:
    app: vault-forge-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
