apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-forge-app
  namespace: vault-forge
  labels:
    app: vault-forge-app
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: vault-forge-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
