apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: vault-forge-app
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          environment: prod
  - target:
      kind: HorizontalPodAutoscaler
      name: vault-forge-app
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
