name: VaultForge Pipeline

on:
  push:
    branches: [main, 'scratch/**']
  pull_request:
    branches: [main, 'scratch/**']

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci-security.yml
    secrets: inherit

  cd:
    name: CD
    needs: ci
    if: github.event_name == 'push' && needs.ci.outputs.image_digest != ''
    uses: ./.github/workflows/cd-deploy.yml
    with:
      image_digest: ${{ needs.ci.outputs.image_digest }}
      overlay: dev
    secrets: inherit
